M48
; DRILL file {KiCad 9.0.7} date 2026-03-10T13:29:48-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-10T13:29:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X143.83Y-78.555
X149.61Y-78.555
T2
X112.71Y-81.72
X112.75Y-37.55
X168.58Y-37.55
X168.62Y-81.87
M30
